create table gravadora (
			 Codigo_Gravadora INTEGER NOT NULL,
             Nome_Gravadora CHAR(60) NULL,
             Endereco CHAR(60) NULL,
             Telefone CHAR(20) NULL,
             Contato  CHAR(20) NULL,
             Url      CHAR(80) NULL
             
);
ALTER TABLE gravadora
    ADD CONSTRAINT XPKGRAVADORA PRIMARY KEY (Codigo_Gravadora);
    
SHOW CREATE TABLE gravadora;
	
create table CD (
		Codigo_CD          INTEGER NOT NULL,
        Codigo_Gravadora   INTEGER NULL,
        Nome_CD            CHAR(60) NULL,
        Preco_Venda        NUMERIC(14,2) NULL,
        Data_Lancamento    DATE NULL,
        CD_Indicado        INTEGER NULL
	);

ALTER TABLE CD ADD  CONSTRAINT XPKCD PRIMARY KEY (Codigo_CD);
SHOW CREATE TABLE CD ;

alter table cd add estilo CHAR(20);

alter table cd add vendas NUMERIC(8,2);

CREATE TABLE MUSICA(
		Codigo_Musica INTEGER NOT NULL,
        Nome_Musica CHAR(60) NULL,
        Duracao     NUMERIC(6,2) NULL
);

ALTER TABLE MUSICA
		ADD CONSTRAINT XPKMUSICA PRIMARY KEY (Codigo_Musica);
        
	
CREATE TABLE MUSICA_AUTOR(
		Codigo_Musica    INTEGER NOT NULL,
        Codigo_Autor     INTEGER NOT NULL
);

ALTER TABLE MUSICA_AUTOR
		ADD CONSTRAINT XPKMUSICA_AUTOR PRIMARY KEY (Codigo_Musica, Codigo_Autor);

CREATE TABLE FAIXA (
		Codigo_Faixa    INTEGER NOT NULL,
        Codigo_Autor      INTEGER NOT NULL,
		Codigo_Album     INTEGER NULL
);
drop table faixa;
ALTER TABLE FAIXA ADD CONSTRAINT XPKFAIXA PRIMARY KEY (Codigo_Musica, Codigo_CD);
    
CREATE TABLE CD_CATEGORIA(
		Codigo_Categoria   INTEGER   NOT NULL,
        Menor_Preco        NUMERIC(14,2) NOT NULL,
        Maior_Preco        NUMERIC(14,2) NOT NULL
	);
    
ALTER TABLE CD
       ADD  CONSTRAINT GRAVADORA_CD  FOREIGN KEY (Codigo_Gravadora) REFERENCES GRAVADORA;
    
ALTER TABLE CD
       ADD  CONSTRAINT CD_CD FOREIGN KEY (CD_Indicado) REFERENCES CD ;
       

ALTER TABLE MUSICA_AUTOR
       ADD  CONSTRAINT AUTOR_MUSICA_AUTOR FOREIGN KEY (Codigo_Autor) REFERENCES AUTOR ;
       
       ALTER TABLE MUSICA_AUTOR
       ADD  CONSTRAINT MUSICA_MUSICA_AUTOR FOREIGN KEY (Codigo_Musica) REFERENCES MUSICA ;
       
ALTER TABLE FAIXA
		ADD CONSTRAINT CD_FAIXA FOREIGN KEY (Codigo_CD) REFERENCES CD;

ALTER TABLE FAIXA
       ADD  CONSTRAINT MUSICA_FAIXA FOREIGN KEY (Codigo_Musica) REFERENCES MUSICA ;	
       



INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 1, 'Será',2.28 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 2, 'Ainda é Cedo', 3.55 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 3, 'Geração Coca-Cola', 2.20 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 4, 'Eduardo e Monica', 4.32 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 5, 'Tempo Perdido', 5.00 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 6, 'Índios', 4.23 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 7, 'Que País é Este',2.64 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 8, 'Faroeste Caboclo', 9.03 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 9, 'Há Tempos', 3.16 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 10, 'Pais e Filhos', 5.06 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 11, 'Meninos e Meninas', 3.22 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 12, 'Vento no Litoral', 6.05 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 13, 'Perfeição', 4.35 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 14, 'Giz', 3.20 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 15, 'Dezesseis', 5.28 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 16, 'Antes das Seis', 3.09 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 17, 'Meninos, Eu Vi', 3.25 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 18, 'Eu Te Amo', 3.06 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 19, 'Piano na Mangueira', 2.23 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 20, 'A Violeira', 2.54 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 21, 'Anos Dourados', 2.56 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 22, 'Olha, Maria', 3.55 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 23, 'Biscate', 3.20 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 24, 'Retrato em Preto e Branco', 3.03 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 25, 'Falando de Amor', 3.20 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 26, 'Pois É', 2.48 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 27, 'Noite dos Mascarados', 2.42 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 28, 'Sabiá', 3.20 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 29, 'Imagina', 2.52 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 30, 'Bate-Boca', 4.41 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 31, 'Cai Dentro', 2.41 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 32, 'O Bêbado e o Equilibrista', 3.47 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 33, 'Essa Mulher', 3.47 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 34, 'Basta de Clamares Inocência', 3.38 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 35, 'Beguine Dodói', 2.14 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 36, 'Eu hein Rosa', 3.36 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 37, 'Altos e Baixos', 3.29 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 38, 'Bolero de Satã', 3.32 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 39, 'Pé Sem Cabeça', 2.57 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 40, 'As Aparências Enganam', 4.18 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 41, 'É o Amor', 4.19 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 42, 'Trenzinho Caipira', 3.32 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 43, 'Luar do Sertão', 3.23 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 44, 'Não tenha Medo', 3.27 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 45, 'Eu queria que você viesse', 2.57 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 46, 'Espere por mim Morena', 3.04 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 47, 'Resto de mim', 2.59 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 48, 'Gema', 2.51 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 49, 'Cacilda', 2.22 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 50, 'Agradecer e abraçar', 3.30 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 51, 'As flores do jardim da nossa casa', 3.26 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 52, 'Romaria', 3.16 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 53, 'A força que nunca seca', 2.17 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 54, 'Vila do Adeus', 3.06 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 55, 'Devolva-me', 3.58 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 56, 'Mais Feliz', 2.50 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 57, 'Inverno', 4.40 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 58, 'Mentiras', 2.58 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 59, 'Esquadros', 3.10 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 60, 'Cariocas', 3.14 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 61, 'Vambora', 4.16 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 62, 'Por isso eu Corro Demais', 2.58 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 63, 'Maresia', 4.09 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 64, 'Metade', 3.25 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 65, 'Senhas', 3.37 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 66, 'Marina', 2.55 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 67, 'Naquela Estação', 4.46 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 68, 'Mandy', 3.18 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 69, 'New York City Rhythm', 4.41 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 70, 'Looks Like We Made It', 3.32 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 71, 'Daybreak', 3.05 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 72, 'Can''t Smile Without you', 3.13 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 73, 'It''s a Miracle', 3.53 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 74, 'Even Now', 3.29 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 75, 'Bandstand Boogie', 2.50 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 76, 'Trying to get the feeling again', 3.50 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 77, 'Some Kind of Friend', 4.02 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 78, 'Praying for Time', 3.52 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 79, 'Freedom 90', 3.52 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 80, 'They Won''t Go When I Go', 3.22 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 81, 'Something to Save', 4.10 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 82, 'Cowboys and Angels', 4.12 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 83, 'Don''t Let the Sun Go Down on Me', 3.45 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 84, 'Waiting for That Day', 2.58 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 85, 'Mothers Pride', 2.12 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 86, 'Heal the Pain', 3.02 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 87, 'Soul Free', 2.42 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 88, 'Waiting', 3.32 );
 INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 89, 'Lição De Baião', 2.15 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 90, 'Oito Anos', 6.39 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 91, 'Lig-Lig-Lig-Lé', 4.26 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 92, 'Fico Assim Sem Você', 3.45 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 93, 'Canção Da Falsa Tartaruga', 1.32 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 94, 'Formiga Bossa Nova', 4.38 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 95, 'Ciranda Da Bailarina', 3.32 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 96, 'Ser De Sagitário', 3.19 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 97, 'Borboleta', 3.46 );
INSERT INTO MUSICA (CODIGO_MUSICA, NOME_MUSICA, DURACAO )
 VALUES ( 98, 'Saiba', 2.12 );
 
 INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 1, 'EMI', 'Rod. Pres. Dutra, s/n – km 229,8', 'www.emi-music.com.br', 'JOÃO' );
INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 2, 'BMG', 'Av. Piramboia, 2898 - Parte 7', 'www.bmg.com.br', 'MARIA' );
INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 3, 'SOM LIVRE', NULL, 'www.somlivre.com.br', 'MARTA' );
INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 4, 'EPIC', NULL, 'www.epic.com.br', 'PAULO' );
 INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 5, 'SONY MUSIC', NULL, 'www.sonymusic.com.br', 'JULIO' );

INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 1, 'EMI', 'Rod. Pres. Dutra, s/n – km 229,8', 'www.emi-music.com.br', 'JOÃO' );
INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 2, 'BMG', 'Av. Piramboia, 2898 - Parte 7', 'www.bmg.com.br', 'MARIA' );
INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 3, 'SOM LIVRE', NULL, 'www.somlivre.com.br', 'MARTA' );
INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 4, 'EPIC', NULL, 'www.epic.com.br', 'PAULO' );
 INSERT INTO GRAVADORA (CODIGO_GRAVADORA, NOME_GRAVADORA, ENDERECO, URL, CONTATO )
 VALUES ( 5, 'SONY MUSIC', NULL, 'www.sonymusic.com.br', 'JULIO' );
 
INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO)
VALUES (1, 1, 'Mais do Mesmo', 15.00, '1998-10-01');

INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO )
 VALUES ( 2, 2, 'Bate-Boca', 12.00,'1998-10-02');
INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO)
VALUES (5, 3, 'Elis Regina - Essa Mulher', 13.00, '1998-02-14');

INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO )
 VALUES ( 8, 2, 'A Força que nunca Seca', 13.50,'1998-02-12');
INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO )
 VALUES ( 9, 3, 'Perfil', 10.50,'1998-02-11');
INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO )
 VALUES ( 10, 2, 'Barry Manilow Greatest Hits Vol I', 9.50,'1999-02-11' );
INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO )
 VALUES ( 11, 2, 'Listen Without Prejudice', 9.00,'1976-02-14' );
INSERT INTO CD (CODIGO_CD, CODIGO_GRAVADORA, NOME_CD, PRECO_VENDA, DATA_LANCAMENTO )
 VALUES ( 14, 5, 'Adriana Partimpim', 21.90, '1999-02-11');
UPDATE CD
   SET CD_INDICADO = 5, estilo = 'Bossa Nova', vendas = 2500
 WHERE CODIGO_CD = 1;
UPDATE CD
   SET CD_INDICADO = 3, estilo = 'MPB', vendas = 800
 WHERE CODIGO_CD = 2;
UPDATE CD
   SET CD_INDICADO = 1, estilo = 'Bossa Nova', vendas = 1500
 WHERE CODIGO_CD = 3;
UPDATE CD
   SET CD_INDICADO = 2, estilo = 'MPB', vendas = 3000
 WHERE CODIGO_CD = 5;
UPDATE CD
   SET CD_INDICADO = 7, estilo = 'Internacional', vendas = 900
 WHERE CODIGO_CD = 6;
UPDATE CD
   SET CD_INDICADO = 1, estilo = 'Internacional', vendas = 200
 WHERE CODIGO_CD = 4;
UPDATE CD
   SET CD_INDICADO = 8, estilo = 'MPB', vendas = 10
 WHERE CODIGO_CD = 8;
 
 
 INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 1, 1, 1 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 2, 2 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 3, 3 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 4, 4 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 5, 5 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 6, 6 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 7, 7 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 8, 8 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 9, 9, 9 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 10, 10, 10 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 11, 11, 11 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 12, 12, 12 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 13, 13, 13 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 14, 14, 14 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 15, 15, 15 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 16, 16, 16 );

INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 1, 17 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 2, 18 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 3, 19 );
INSERT INTO FAIXA (CODIGO_CD, NUMERO_FAIXA, CODIGO_MUSICA )
 VALUES ( 2, 4, 20 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 5, 21 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 6, 22 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 7, 23 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 8 ,24 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 9, 25 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 10, 26 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 11, 27 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 12, 28 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 13, 29 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 2, 14, 30 );

INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 1, 31 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 2, 32 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 3, 33 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 4, 34 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 5, 35 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 6, 36 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 7, 37 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 8 ,38 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 9, 39 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 3, 10, 40 );

INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 1, 41 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 2, 42 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 3, 43 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 4, 44 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 5, 45 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 6, 46 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 7, 47 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 8 ,48 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 9, 49 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 10, 50 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 11, 51 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 12, 52 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 13, 53 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 4, 14, 54 );

INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 1, 55 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 2, 56 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 3, 57 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 4, 58 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 5, 59 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 6, 60 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 7, 61 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 8 ,62 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 9, 63 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 10, 64 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 11, 65 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 12, 66 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 5, 13, 67 );

INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 1, 68 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 2, 69 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 3, 70 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 4, 71 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 5, 72 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 6, 73 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 7, 74 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 8 ,75 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 9, 76 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 6, 10, 77 );
-- LISTEN WITHOUT PREJUDICE
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 1, 78 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 2, 79 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 3, 80 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 4, 81 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 5, 82 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 6, 83 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 7, 84 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 8 ,85 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 9, 86 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 10, 87 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 7, 11, 88 );

INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 1, 89 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 2, 90 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 3, 91 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 4, 92 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 5, 93 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 6, 94 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 7, 95 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 8, 96 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 9, 97 );
INSERT INTO FAIXA (CODIGO_FAIXA, CODIGO_AUTOR, CODIGO_ALBUM )
 VALUES ( 8, 10, 98 );
 
 

